CREATE DATABASE EXPENDIO;
GO

USE EXPENDIO;
GO

CREATE TABLE PROVEEDOR (
    PRO_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRO_NOMBRE VARCHAR(40) NOT NULL
);
GO

CREATE TABLE CATEGORIA (
    CAT_ID INT IDENTITY(1,1) PRIMARY KEY,
    CAT_DESCRIPCION VARCHAR(25) NOT NULL
);
GO

CREATE TABLE PRODUCTO (
    PDT_ID INT IDENTITY(1,1) PRIMARY KEY,
    PDT_ID_CATEGORIA INT NOT NULL,
    PDT_DESCRIPCION VARCHAR(30) NOT NULL,
    PDT_PRECIO FLOAT NOT NULL,
    PDT_INVENTARIO INT NOT NULL,
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (PDT_ID_CATEGORIA)
        REFERENCES CATEGORIA (CAT_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
GO

CREATE TABLE EMPLEADO (
    EMP_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMP_NOMBRE VARCHAR(20) NOT NULL,
    EMP_APELLIDO VARCHAR(20) NOT NULL,
    EMP_TIPO INT NOT NULL
);
GO

CREATE TABLE DEUDOR (
    DEU_ID INT IDENTITY(1,1) PRIMARY KEY,
    DEU_NOMBRE VARCHAR(20) NOT NULL,
    DEU_APELLIDO VARCHAR(20) NOT NULL,
    DEU_SALDO FLOAT NOT NULL DEFAULT 0
);
GO

CREATE TABLE VENTA (
    VEN_ID INT IDENTITY(1,1) PRIMARY KEY,
    VEN_ID_EMPLEADO INT NOT NULL,
    VEN_ID_CLIENTE INT NULL,
    VEN_FECHA DATE NOT NULL,
    VEN_TOTAL FLOAT NOT NULL,
    CONSTRAINT FK_VENTA_EMPLEADO FOREIGN KEY (VEN_ID_EMPLEADO)
        REFERENCES EMPLEADO (EMP_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_VENTA_DEUDOR FOREIGN KEY (VEN_ID_CLIENTE)
        REFERENCES DEUDOR (DEU_ID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);
GO

CREATE TABLE VENTA_DETALLE (
    VED_ID INT IDENTITY(1,1) PRIMARY KEY,
    VED_ID_VENTA INT NOT NULL,
    VED_ID_PRODUCTO INT NOT NULL,
    VED_CANTIDAD INT NOT NULL,
    VED_SUBTOTAL FLOAT NOT NULL,
    CONSTRAINT FK_VENTADET_VENTA FOREIGN KEY (VED_ID_VENTA)
        REFERENCES VENTA (VEN_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_VENTADET_PRODUCTO FOREIGN KEY (VED_ID_PRODUCTO)
        REFERENCES PRODUCTO (PDT_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
GO

CREATE TABLE COMPRA (
    COM_ID INT IDENTITY(1,1) PRIMARY KEY,
    COM_ID_PROVEEDOR INT NOT NULL,
    COM_ID_EMPLEADO INT NOT NULL,
    COM_FECHA DATE NOT NULL,
    COM_TOTAL FLOAT NOT NULL,
    CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY (COM_ID_PROVEEDOR)
        REFERENCES PROVEEDOR (PRO_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_COMPRA_EMPLEADO FOREIGN KEY (COM_ID_EMPLEADO)
        REFERENCES EMPLEADO (EMP_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
GO

CREATE TABLE COMPRA_DETALLE (
    COD_ID INT IDENTITY(1,1) PRIMARY KEY,
    COD_ID_COMPRA INT NOT NULL,
    COD_ID_PRODUCTO INT NOT NULL,
    COD_CANTIDAD INT NOT NULL,
    COD_SUBTOTAL FLOAT NOT NULL,
    CONSTRAINT FK_COMPRADET_COMPRA FOREIGN KEY (COD_ID_COMPRA)
        REFERENCES COMPRA (COM_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_COMPRADET_PRODUCTO FOREIGN KEY (COD_ID_PRODUCTO)
        REFERENCES PRODUCTO (PDT_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
GO
